version: '3'
services:
  kibana:
    image: kibana:6.5.4
    links:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: elasticsearch:6.5.4
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata1:
    driver: local
