version: '3'
services:
  kibana:
    image: kibana:6.5.4
    container_name: kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: elasticsearch:6.5.4
    container_name: elasticsearch
    cap_add:
      - IPC_LOCK
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  es-data:
    driver: local
