version: '3'

services:
  minio:
    image: minio/minio
    volumes:
    - minio-data:/export
    ports:
    - "19000:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: server /export

volumes:
  minio-data:
    driver: local
