version: '3'

services:
  minio1:
    image: minio/minio
    volumes:
      - minio-data1:/export
    ports:
      - "19001:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: server http://minio{1...4}/export
  minio2:
    image: minio/minio
    volumes:
      - minio-data2:/export
    ports:
      - "19002:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: server http://minio{1...4}/export
  minio3:
    image: minio/minio
    volumes:
      - minio-data3:/export
    ports:
      - "19003:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: server http://minio{1...4}/export
  minio4:
    image: minio/minio
    volumes:
      - minio-data4:/export
    ports:
      - "19004:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: server http://minio{1...4}/export

volumes:
  minio-data1:
    driver: local
  minio-data2:
    driver: local
  minio-data3:
    driver: local
  minio-data4:
    driver: local
